name: Update README with Directory Structure

on:
  push:
    branches:
      - main
    paths:
      - 'Functional Income Statements/**'
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tree
        run: sudo apt-get install -y tree

      - name: Run directory structure script
        run: bash generate_directory_structure.sh

      - name: Update README
        run: |
          echo "# Domo_Dataflows" > README.md
          echo "" >> README.md
          echo "## Functional Income Statements Directory Structure" >> README.md
          echo "" >> README.md
          cat directory_structure.md >> README.md

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add README.md directory_structure.md
          git commit -m "Update README with latest directory structure" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
